version: '3.5'

services:

  local_sensing_intest:
    build:
      context: .
      args: 
        - CACHBUST=""
        - SSH_PRIVATE_KEY
      network: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true
    entrypoint: /ros_entrypoint.sh
    command: >
      bash -c "bash"
    tty: true

        --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \